name = "take-a-net"
main = "src/cloudflare.worker.js"
compatibility_date = "2023-10-30"

minify = false

[site]
bucket = "./dist"

[env.dev.vars]
IS_CLOUDFLARE_WORKER = true
APP_NAME = "take-a-net"
ENV = "dev"

[env.qa.vars]
IS_CLOUDFLARE_WORKER = true
APP_NAME = "take-a-net"
ENV = "qa"

[env.prod.vars]
IS_CLOUDFLARE_WORKER = true
APP_NAME = "take-a-net"
ENV = "prod"